#??????8080--??????
server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jiajiao?user=root&password=20020516&useUnicode=true
    username: root
    password: 20020516

mybatis:
  mapper-locations: classpath:mapper/*.xml    #????mybatis??
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl